def donnee();
  exCaisse = int(input("quels sont vos anciennes caisses ? "))
  recettePublique = int(input("quels sont vos recette publique en % mais sans le <<%>> ?"))
  annexion = int(input("quel est le total du PIB des pays que vous avez annexé ?"))
  tauxDePertePopularite = int(input("par combien votre population est-elle divisé pour calculer votre popularité (si vous ne savez pas, contactez le staff) ?"))
  population = int(input("quel est votre population ?"))
  Musee = int(input("combien de musée avez vous construit ?"))
  Propagande = int(input("combien de propagande avez vous fait ?"))
  Cinemas = int(input("combien de cinéma avez vous construit ?"))
  Usine = int(input("combien d'usine avez vous construit ?"))
  Nucleaire = int(input("combien de centrale nucléaire avez vous construit ?"))
  Ferme = int(input("combien de ferme avez vous construit ?"))
  Port = int(input("combien de port avez vous construit ?"))
  PopulariteArbitrairePerdu = int(input("Combien de popularité les MJ/roll vous ont fait perdre ?"))
  PopulariteArbitraireGagne = int(input("Combien de popularité les MJ/roll vous ont fait gagner ?"))
